# Generated by Django 4.1.7 on 2023-05-08 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_departamento', models.CharField(max_length=50)),
                ('precio_departamento', models.IntegerField()),
                ('direccion_departamento', models.CharField(max_length=50)),
                ('metros_departamento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
                ('id_departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='real_back.departamento')),
            ],
        ),
    ]
