# Generated by Django 4.1.7 on 2023-05-25 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicasPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metros_totales', models.IntegerField(default=0)),
                ('metros_utiles', models.IntegerField(default=0)),
                ('cant_dormitorios', models.IntegerField()),
                ('cant_banos', models.IntegerField()),
                ('permite_mascotas', models.IntegerField()),
                ('tiene_bodega', models.IntegerField()),
                ('tiene_estacionamiento', models.IntegerField()),
            ],
            options={
                'ordering': ['id_propiedad'],
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['id_comuna'],
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id_propiedad', models.AutoField(primary_key=True, serialize=False)),
                ('valor_propiedad', models.IntegerField()),
                ('es_arriendo', models.IntegerField()),
                ('es_venta', models.IntegerField()),
                ('id_comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='real_back.comuna')),
            ],
            options={
                'ordering': ['id_propiedad'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=70)),
                ('capital_region', models.CharField(default='', max_length=30)),
            ],
            options={
                'ordering': ['id_region'],
            },
        ),
        migrations.CreateModel(
            name='TipoPropiedad',
            fields=[
                ('id_tipo_propiedad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_propiedad', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['id_tipo_propiedad'],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id_visita', models.AutoField(primary_key=True, serialize=False)),
                ('dia_visita', models.DateField()),
                ('hora_visita', models.TimeField()),
                ('nombre_completo', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=11)),
                ('id_propiedad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='real_back.propiedad')),
            ],
            options={
                'ordering': ['id_visita'],
            },
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_departamento',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='id_tipo_propiedad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='real_back.tipopropiedad'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='real_back.region'),
        ),
        migrations.AddField(
            model_name='caracteristicaspropiedad',
            name='id_propiedad',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='real_back.propiedad'),
        ),
    ]
